# Regenerates src/trig_tables.jl.
# Run from the package root:  julia --project=. scripts/gen_trig_tables.jl
#
# Generates minimax coefficient tables for the sinpi / cospi kernels, evaluated
# on the reduced argument interval x in [-1/4, 1/4] (t = x^2 in [0, 1/16]):
#
#   sinpi(x) = x * P(t),      P(t) ~ sin(pi*sqrt(t))/sqrt(t),  P(0) = pi
#   cospi(x) = 1 + t * R(t),  R(t) ~ (cos(pi*sqrt(t)) - 1)/t,  R(0) = -pi^2/2
#
# The leading 1 of cospi is reconstructed exactly outside the polynomial; sinpi
# keeps its pi leading coefficient inside P (normalizing it out would cost an
# extra multiply by the pi constant). Both are fit with a relative objective.

include(joinpath(@__DIR__, "Remez.jl"))
using .Remez: minimax_polynomial
using Printf: @sprintf

# Split a BigFloat into N non-overlapping limbs of type T (round-to-nearest),
# matching what MultiFloat{T,N}(::BigFloat) produces. Done directly here so the
# generator does not depend on loading MultiFloats (which would require this
# table to already exist).
function _to_limbs(::Type{T}, N::Int, x::BigFloat) where {T}
    ls = Vector{T}(undef, N)
    r = x
    for j = 1:N
        h = T(r)
        ls[j] = h
        r -= h
    end
    return ls
end

const GUARD = 3

# Result precision of MultiFloat{T,N} in bits (matches Base.precision on the
# type): N limbs, but adjacent limbs share one bit of overlap headroom.
_mfprec(::Type{T}, N::Int) where {T} = N * (precision(T) - 1) + 1

# Reduced-argument bound, padded a few ulps above 1/16 to absorb the tiny
# overshoot from reducing on the first limb only (|rx| <= 1/4 + O(2^-52)).
_tmax() = (BigFloat(1) / 16) * (1 + BigFloat(2)^-20)

# Value of the d-th derivative at t of a power series sum_{n>=0} a_n t^n, where
# a_0 = a0 and a_n/a_{n-1} = ratio(n). Evaluated from the series so t = 0 (the
# left endpoint, which Remez probes) has no removable-singularity trouble.
function _dseries(t::BigFloat, a0::BigFloat, ratio, d::Int)
    a = a0
    n = 0
    while n < d            # advance coefficient to a_d
        n += 1
        a *= ratio(n)
    end
    s = zero(t)
    tn = one(t)            # t^(n-d)
    while true
        ff = one(t)        # falling factorial n*(n-1)*...*(n-d+1)
        for k = 0:d-1
            ff *= (n - k)
        end
        term = ff * a * tn
        s += term
        if n > d + 2 && abs(term) < abs(s) * eps(BigFloat) + eps(BigFloat)
            break
        end
        n > 100000 && break
        n += 1
        a *= ratio(n)
        tn *= t
    end
    return s
end

# Format a Float32/Float64 as an exact hex-float literal in the house style,
# e.g. "+0x1.921FB54442D18p+0001" (wrapped in Float32(...) for Float32).
function _hexlit(x::T) where {T<:Union{Float32,Float64}}
    sgn = signbit(x) ? "-" : "+"
    s = @sprintf("%a", abs(Float64(x)))
    mant, exp = split(s, 'p')
    body = replace(uppercase(mant), "0X" => "0x")
    estr = @sprintf("%+05d", parse(Int, exp))
    lit = string(sgn, body, "p", estr)
    return T === Float32 ? "Float32($lit)" : lit
end

# Truncate coefficient c to only the limbs that stay significant in the final
# result. Coefficient c is multiplied by `tfactor` (= tmax^(power of t in the
# result) ) and the result has reference magnitude `ref`, so limb j contributes
# ~ |limb_j| * tfactor relative to a result ulp of ref * 2^-(p+guard). Drop a
# limb once it falls below that. Always keep at least one limb.
function _significant_limbs(::Type{T}, ::Val{N}, c::BigFloat,
    tfactor::BigFloat, ref::BigFloat, guard::Int) where {T,N}
    p = _mfprec(T, N)
    ls = _to_limbs(T, N, c)
    thresh = ldexp(abs(ref), -(p + guard))
    last = 1
    for j = 1:N
        (abs(BigFloat(ls[j])) * tfactor >= thresh) || break
        last = j
    end
    return ntuple(j -> ls[j], last)
end

# Search for the lowest-degree minimax polynomial meeting the precision target.
function _minimax(f, df, d2f, b::BigFloat, target::Int)
    for deg = 1:64
        c, _, E = minimax_polynomial(f, df, d2f, BigFloat(0), b, Val{deg}();
            objective=:relative)
        abs(E) < BigFloat(2)^(-target) && return c
    end
    error("minimax did not converge")
end

function _emit(io, name, accessor, T, N, coeffs, tfactor_of, ref)
    println(io, "@inline $accessor(::Type{$T}, ::Val{$N}) = ( # spellchecker: disable")
    for (i, c) in enumerate(coeffs)        # i = 1 => degree 0
        ls = _significant_limbs(T, Val{N}(), c, tfactor_of(i - 1), ref, GUARD)
        println(io, "    (", join(_hexlit.(ls), ", "), ",),")
    end
    println(io, ") # spellchecker: enable")
    println(io)
end

open(joinpath(@__DIR__, "..", "src", "trig_tables.jl"), "w") do io
    println(io, "# AUTOGENERATED by scripts/gen_trig_tables.jl -- do not edit by hand.")
    println(io)
    for T in (Float32, Float64), N in 1:4
        p = _mfprec(T, N)
        # GUARD bits below the result ulp: terms/limbs contributing less than
        # 2^-(p+GUARD) of the result cannot affect a representable bit, so we
        # neither generate them (Remez target) nor store them (limb dropping).
        # 3 leaves enough margin that dropped tails can't accumulate past ~1 ulp.
        target = p + GUARD
        setprecision(BigFloat, 2 * p + 64) do
            b = _tmax()
            pi_big = BigFloat(pi)
            pi2 = pi_big * pi_big

            # --- sinpi: P(t) ~ sin(pi sqrt t)/sqrt t, a_0 = pi,
            #     a_n/a_{n-1} = -pi^2 / ((2n)(2n+1)). Result = x*P(t): coefficient
            #     of degree k carries factor t^k, reference magnitude P(0) = pi.
            sratio = n -> -pi2 / (BigFloat(2n) * BigFloat(2n + 1))
            sf = t -> _dseries(t, pi_big, sratio, 0)
            sdf = t -> _dseries(t, pi_big, sratio, 1)
            sd2f = t -> _dseries(t, pi_big, sratio, 2)
            scoef = _minimax(sf, sdf, sd2f, b, target)
            _emit(io, "sinpi", "_sinpi_coefficients", T, N, scoef,
                k -> b^k, pi_big)

            # --- cospi: R(t) ~ (cos(pi sqrt t) - 1)/t, b_0 = -pi^2/2,
            #     b_m/b_{m-1} = -pi^2 / ((2m+1)(2m+2)). Result = 1 + t*R(t):
            #     coefficient of degree k carries factor t^(k+1), reference 1.
            cratio = m -> -pi2 / (BigFloat(2m + 1) * BigFloat(2m + 2))
            cf = t -> _dseries(t, -pi2 / 2, cratio, 0)
            cdf = t -> _dseries(t, -pi2 / 2, cratio, 1)
            cd2f = t -> _dseries(t, -pi2 / 2, cratio, 2)
            ccoef = _minimax(cf, cdf, cd2f, b, target)
            _emit(io, "cospi", "_cospi_coefficients", T, N, ccoef,
                k -> b^(k + 1), BigFloat(1))
        end
    end
end

println("Wrote src/trig_tables.jl")
