# Regenerates src/atan_tables.jl.
# Run from the package root:  julia --project=. scripts/gen_atan_tables.jl

include(joinpath(@__DIR__, "Remez.jl"))
using .Remez: minimax_polynomial
using MultiFloats: MultiFloat
using Printf: @sprintf

# Number of half-angle reduction steps per (limb type, N). Tuned to balance
# k*(sqrt+div) reduction cost against polynomial degree.
const KMAP = Dict(
    (Float32, 1) => 2, (Float32, 2) => 3, (Float32, 3) => 3, (Float32, 4) => 4,
    (Float64, 1) => 3, (Float64, 2) => 4, (Float64, 3) => 5, (Float64, 4) => 5,
)

# Number of limbs stored in the full-precision pi table (matches the style of
# _LN_2_FULL_* in src/log.jl).
const PI_LIMBS = Dict(Float32 => 6, Float64 => 20)

# g(u) = atan(sqrt(u))/sqrt(u) = sum_{j>=0} (-1)^j u^j / (2j+1), and its first
# two derivatives in u. Computed from the series (no division by u, so u=0 is
# fine). All in BigFloat at the currently-set precision.
function _g(u::BigFloat)
    s = one(u); sign = -one(u); pj = u; j = 1
    while true
        term = sign * pj / (2j + 1)
        s += term
        (j > 2 && abs(term) < abs(s) * eps(BigFloat)) && break
        sign = -sign; pj *= u; j += 1; j > 20000 && break
    end
    return s
end
function _dg(u::BigFloat)
    s = zero(u); sign = -one(u); pjm1 = one(u); j = 1
    while true
        term = sign * j * pjm1 / (2j + 1)
        s += term
        (j > 2 && abs(term) < abs(s) * eps(BigFloat) + eps(BigFloat)) && break
        sign = -sign; pjm1 *= u; j += 1; j > 20000 && break
    end
    return s
end
function _d2g(u::BigFloat)
    s = zero(u); sign = one(u); pjm2 = one(u); j = 2
    while true
        term = sign * j * (j - 1) * pjm2 / (2j + 1)
        s += term
        (j > 3 && abs(term) < abs(s) * eps(BigFloat) + eps(BigFloat)) && break
        sign = -sign; pjm2 *= u; j += 1; j > 20000 && break
    end
    return s
end

# Format a Float32/Float64 as an exact hex-float literal in the house style,
# e.g. "+0x1.921FB54442D18p+0001" (and wrapped in Float32(...) for Float32).
function _hexlit(x::T) where {T<:Union{Float32,Float64}}
    sgn = signbit(x) ? "-" : "+"
    s = @sprintf("%a", abs(Float64(x)))      # "0x1.xxxxp+n"
    mant, exp = split(s, 'p')
    body = replace(uppercase(mant), "0X" => "0x")
    estr = @sprintf("%+05d", parse(Int, exp))
    lit = string(sgn, body, "p", estr)
    return T === Float32 ? "Float32($lit)" : lit
end

# Keep the first `m` limbs of x's N-limb representation (limbs are stored in
# decreasing magnitude, so this is the best m-limb truncation).
function _limbs(::Type{T}, ::Val{N}, x::BigFloat, m::Int) where {T,N}
    ls = MultiFloat{T,N}(x)._limbs
    return ntuple(i -> ls[i], m)
end

# How many leading limbs of a coefficient are worth keeping: limb j of the
# coefficient contributes |limb_j| * contrib_scale to the order-1 result (where
# contrib_scale = B^(i-1) accounts for the u^(i-1) it multiplies). Keep limbs
# while that stays at or above 2^-target; drop the rest (they round off). This
# trims BigFloat rounding noise (e.g. a spurious tiny low limb) automatically.
function _keep_count(
    ls::NTuple{N,T}, contrib_scale::BigFloat, target::Int,
) where {N,T}
    thresh = BigFloat(2)^(-target)
    m = 1
    for j in 1:N
        if abs(BigFloat(ls[j])) * contrib_scale >= thresh
            m = j
        else
            break   # limbs decrease in magnitude, so the rest are below too
        end
    end
    return m
end

open(joinpath(@__DIR__, "..", "src", "atan_tables.jl"), "w") do io
    println(io, "# AUTOGENERATED by scripts/gen_atan_tables.jl -- do not edit by hand.")
    println(io)

    # ---- pi constant tables ----
    for (T, suffix) in ((Float32, "F32"), (Float64, "F64"))
        nl = PI_LIMBS[T]
        setprecision(BigFloat, nl * precision(T) + 32) do
            ls = MultiFloat{T,nl}(BigFloat(pi))._limbs
            println(io, "const _PI_FULL_$suffix = (")
            for v in ls
                println(io, "    ", _hexlit(v), ",")
            end
            println(io, ")")
            println(io)
        end
    end

    # ---- half-angle step counts and direct-evaluation threshold ----
    # tmax = tan(pi/2^(k+2)) bounds the reduced argument; r <= tmax is evaluated
    # directly (no half-angle reduction, avoiding 1+r^2 precision loss).
    for T in (Float32, Float64), N in 1:4
        k = KMAP[(T, N)]
        println(io, "@inline _atan_halvings(::Type{$T}, ::Val{$N}) = Val{$k}()")
    end
    println(io)
    for T in (Float32, Float64), N in 1:4
        k = KMAP[(T, N)]
        tmax = setprecision(BigFloat, 256) do
            T(tan(BigFloat(pi) / BigFloat(2)^(k + 2)))
        end
        println(io, "@inline _atan_tmax(::Type{$T}, ::Val{$N}) = ", _hexlit(tmax))
    end
    println(io)

    # ---- minimax coefficient tables ----
    for T in (Float32, Float64), N in 1:4
        k = KMAP[(T, N)]
        prec = precision(T)
        target = precision(MultiFloat{T,N}) + 8
        coeffs, B = setprecision(BigFloat, 2 * precision(MultiFloat{T,N}) + 64) do
            # reduced argument bound: r in [0,1] => atan(r) <= pi/4, halved k times
            b = tan(BigFloat(pi) / BigFloat(2)^(k + 2))
            Bsq = b * b
            local best = nothing
            for deg in 1:80
                c, _, E = minimax_polynomial(
                    _g, _dg, _d2g, BigFloat(0), Bsq, Val{deg}();
                    objective=:relative,
                    fixed_coefficients=(0 => BigFloat(1),))
                if abs(E) < BigFloat(2)^(-target)
                    best = c
                    break
                end
            end
            best === nothing && error("atan minimax did not converge for $T x$N")
            return (best, Bsq)
        end
        # The constant term is pinned to 1; we drop it and reconstruct atan as
        # t + t*u*Q(t^2), where Q holds the remaining coefficients. This keeps
        # the dominant term t exact and removes a full-width (1,0,...) row.
        #
        # Significance taper: coefficient a_{i-1} multiplies u^(i-1) (u = t^2),
        # so its contribution magnitude is |a_{i-1}| * B^(i-1). Keep only the
        # limbs that survive rounding at the target precision, enforcing a
        # non-increasing count (required by _horner_expr_mf).
        println(io, "@inline _atan_coefficients(::Type{$T}, ::Val{$N}) = (")
        prev = N
        setprecision(BigFloat, 2 * precision(MultiFloat{T,N}) + 64) do
            for (i, c) in enumerate(coeffs)
                i == 1 && continue          # drop the pinned constant a_0 = 1
                ls = MultiFloat{T,N}(c)._limbs
                m = min(prev, _keep_count(ls, B^(i - 1), target))
                prev = m
                println(io, "    (", join(_hexlit.(ntuple(j -> ls[j], m)), ", "), ",),")
            end
        end
        println(io, ")")
        println(io)
    end
end

println("Wrote src/atan_tables.jl")
