# Coeficcients generated by scripts/gen_atan_tables.jl

const _PI_FULL_F32 = ( # spellchecker: disable
    Float32(+0x1.921FB6p+0001), Float32(-0x1.777A5Cp-0024),
    Float32(-0x1.EE59DAp-0049), Float32(+0x1.98A2Ep-0076),
    Float32(+0x1.B839A2p-0103), Float32(+0x1.48127p-0129),
) # spellchecker: enable

const _PI_FULL_F64 = ( # spellchecker: disable
    +0x1.921FB54442D18p+0001, +0x1.1A62633145C07p-0053,
    -0x1.F1976B7ED8FBCp-0109, +0x1.4CF98E804177Dp-0163,
    +0x1.31D89CD9128A5p-0217, +0x1.0F31C6809BBDFp-0275,
    +0x1.519B3CD3A431Bp-0330, +0x1.8158536F92F8Ap-0385,
    +0x1.BA7F09AB6B6A9p-0441, -0x1.EDD0DBD2544CFp-0497,
    +0x1.79FB1BD1310BAp-0552, +0x1.A637ED6B0BFF6p-0606,
    -0x1.A485FCA40908Ep-0661, -0x1.E501295D98169p-0716,
    -0x1.160DBEE83B4Ep-0770,  -0x1.9B6D799AE131Cp-0826,
    +0x1.6CF70801F2E28p-0880, +0x1.63BF0598DA483p-0934,
    +0x1.871574E69A459p-0988, -0x1.5C0B6CCp-1048,
) # spellchecker: enable

# Full-precision pi accessors (take the first N limbs of the generated table,
# mirroring _ln_2 in src/log.jl).
@inline _pi(::Type{_MF{Float32,N}}) where {N} =
    _MF{Float32,N}(ntuple(i -> _PI_FULL_F32[i], Val{N}()))
@inline _pi(::Type{_MF{Float64,N}}) where {N} =
    _MF{Float64,N}(ntuple(i -> _PI_FULL_F64[i], Val{N}()))

# pi/2 is just pi with each limb exponent decremented (exact); no separate table.
@inline _half_pi(::Type{_MF{T,N}}) where {T,N} = unsafe_ldexp(_pi(_MF{T,N}), -1)

@inline _atan_halvings(::Type{Float32}, ::Val{1}) = Val{2}()
@inline _atan_halvings(::Type{Float32}, ::Val{2}) = Val{3}()
@inline _atan_halvings(::Type{Float32}, ::Val{3}) = Val{3}()
@inline _atan_halvings(::Type{Float32}, ::Val{4}) = Val{4}()
@inline _atan_halvings(::Type{Float64}, ::Val{1}) = Val{3}()
@inline _atan_halvings(::Type{Float64}, ::Val{2}) = Val{4}()
@inline _atan_halvings(::Type{Float64}, ::Val{3}) = Val{5}()
@inline _atan_halvings(::Type{Float64}, ::Val{4}) = Val{5}()

@inline _atan_tmax(::Type{Float32}, ::Val{1}) = Float32(+0x1.975F5Ep-0003)
@inline _atan_tmax(::Type{Float32}, ::Val{2}) = Float32(+0x1.936BB8p-0004)
@inline _atan_tmax(::Type{Float32}, ::Val{3}) = Float32(+0x1.936BB8p-0004)
@inline _atan_tmax(::Type{Float32}, ::Val{4}) = Float32(+0x1.927278p-0005)
@inline _atan_tmax(::Type{Float64}, ::Val{1}) = +0x1.936BB8C5B2DA2p-0004
@inline _atan_tmax(::Type{Float64}, ::Val{2}) = +0x1.927278A3B1162p-0005
@inline _atan_tmax(::Type{Float64}, ::Val{3}) = +0x1.92346247A91Fp-0006
@inline _atan_tmax(::Type{Float64}, ::Val{4}) = +0x1.92346247A91Fp-0006

@inline _atan_coefficients(::Type{Float32}, ::Val{1}) = (
    (Float32(-0x1.555554p-0002),),
    (Float32(+0x1.9997Cp-0003),),
    (Float32(-0x1.24040Cp-0003),),
    (Float32(+0x1.A511F2p-0004),),
)

@inline _atan_coefficients(::Type{Float32}, ::Val{2}) = (
    (Float32(-0x1.555556p-0002), Float32(+0x1.555556p-0027),),
    (Float32(+0x1.99999Ap-0003), Float32(-0x1.99B914p-0029),),
    (Float32(-0x1.24924Ap-0003), Float32(+0x1.DFF06p-0028),),
    (Float32(+0x1.C71C4p-0004),),
    (Float32(-0x1.743F1Cp-0004),),
    (Float32(+0x1.32167p-0004),),
)

@inline _atan_coefficients(::Type{Float32}, ::Val{3}) = (
    (Float32(-0x1.555556p-0002), Float32(+0x1.555556p-0027), Float32(-0x1.55545Ap-0052),),
    (Float32(+0x1.99999Ap-0003), Float32(-0x1.99999Ap-0029), Float32(+0x1.32EFD6p-0055),),
    (Float32(-0x1.24924Ap-0003), Float32(+0x1.B6DBA8p-0028), Float32(-0x1.F8D19Cp-0053),),
    (Float32(+0x1.C71C72p-0004), Float32(-0x1.CAFA86p-0031),),
    (Float32(-0x1.745D16p-0004), Float32(-0x1.63C1B2p-0029),),
    (Float32(+0x1.3B134Ap-0004), Float32(+0x1.A998F6p-0032),),
    (Float32(-0x1.10E74Ep-0004),),
    (Float32(+0x1.CFA0D2p-0005),),
)

@inline _atan_coefficients(::Type{Float32}, ::Val{4}) = (
    (Float32(-0x1.555556p-0002), Float32(+0x1.555556p-0027), Float32(-0x1.555556p-0052), Float32(+0x1.5555AAp-0077),),
    (Float32(+0x1.99999Ap-0003), Float32(-0x1.99999Ap-0029), Float32(+0x1.99999Ap-0055), Float32(-0x1.7A3BEEp-0080),),
    (Float32(-0x1.24924Ap-0003), Float32(+0x1.B6DB6Ep-0028), Float32(-0x1.248E8p-0054),),
    (Float32(+0x1.C71C72p-0004), Float32(-0x1.C71C72p-0031), Float32(-0x1.A24E76p-0059),),
    (Float32(-0x1.745D18p-0004), Float32(+0x1.745D98p-0029),),
    (Float32(+0x1.3B13B2p-0004), Float32(-0x1.8BBACp-0029),),
    (Float32(-0x1.11110Ep-0004), Float32(-0x1.C99F4Ap-0029),),
    (Float32(+0x1.E1DBD6p-0005), Float32(+0x1.584628p-0030),),
    (Float32(-0x1.AA825Ap-0005),),
)

@inline _atan_coefficients(::Type{Float64}, ::Val{1}) = (
    (-0x1.555555555554Dp-0002,),
    (+0x1.9999999991BAFp-0003,),
    (-0x1.2492491007D02p-0003,),
    (+0x1.C71C40737F9E8p-0004,),
    (-0x1.743F1CD314481p-0004,),
    (+0x1.3216709EF1114p-0004,),
)

@inline _atan_coefficients(::Type{Float64}, ::Val{2}) = (
    (-0x1.5555555555555p-0002, -0x1.555555555554Ep-0056,),
    (+0x1.999999999999Ap-0003, -0x1.99999999E0E2Dp-0057,),
    (-0x1.2492492492492p-0003, -0x1.2492418DE6BAFp-0057,),
    (+0x1.C71C71C71C71Cp-0004, +0x1.C64FAC906BD08p-0058,),
    (-0x1.745D1745D1744p-0004, -0x1.129427E87C494p-0058,),
    (+0x1.3B13B13B133A6p-0004, -0x1.E824315A25269p-0058,),
    (-0x1.1111110FA4C99p-0004,),
    (+0x1.E1E1DC4BF1ACFp-0005,),
    (-0x1.AF219FFC39185p-0005,),
    (+0x1.816C8F3F7236p-0005,),
)

@inline _atan_coefficients(::Type{Float64}, ::Val{3}) = (
    (-0x1.5555555555555p-0002, -0x1.5555555555555p-0056, -0x1.5555555554859p-0110,),
    (+0x1.999999999999Ap-0003, -0x1.999999999999Ap-0057, +0x1.999996CD698FBp-0111,),
    (-0x1.2492492492492p-0003, -0x1.2492492492492p-0057, -0x1.22E3BD32EE1AAp-0111,),
    (+0x1.C71C71C71C71Cp-0004, +0x1.C71C71C71C6DCp-0058, -0x1.D3878BC207B1Fp-0112,),
    (-0x1.745D1745D1746p-0004, +0x1.745D174740589p-0059,),
    (+0x1.3B13B13B13B14p-0004, -0x1.3B13C5DC43D2Cp-0058,),
    (-0x1.1111111111111p-0004, -0x1.0AE13FF03EC7p-0060,),
    (+0x1.E1E1E1E1E1E14p-0005, -0x1.EB2DA160D5936p-0065,),
    (-0x1.AF286BCA1545Ep-0005, -0x1.08A90DCDCC68Fp-0060,),
    (+0x1.86186163CDFBBp-0005,),
    (-0x1.642C000D3B287p-0005,),
    (+0x1.467F8E89A10DAp-0005,),
)

@inline _atan_coefficients(::Type{Float64}, ::Val{4}) = (
    (-0x1.5555555555555p-0002, -0x1.5555555555555p-0056, -0x1.5555555555555p-0110, -0x1.555555554B83Fp-0164,),
    (+0x1.999999999999Ap-0003, -0x1.999999999999Ap-0057, +0x1.999999999999Ap-0111, -0x1.9999D3A0CAD6Cp-0165,),
    (-0x1.2492492492492p-0003, -0x1.2492492492492p-0057, -0x1.2492492492492p-0111, -0x1.D0A120A65B641p-0166,),
    (+0x1.C71C71C71C71Cp-0004, +0x1.C71C71C71C71Cp-0058, +0x1.C71C71C71B737p-0112, +0x1.19020BB1C0A76p-0167,),
    (-0x1.745D1745D1746p-0004, +0x1.745D1745D1746p-0059, -0x1.745D1605240Fp-0114,),
    (+0x1.3B13B13B13B14p-0004, -0x1.3B13B13B13B14p-0058, +0x1.3B0329F8CD858p-0112,),
    (-0x1.1111111111111p-0004, -0x1.111111111110Fp-0060, +0x1.29898516A0F24p-0114,),
    (+0x1.E1E1E1E1E1E1Ep-0005, +0x1.E1E1E1E1DA2ACp-0061, +0x1.B6734EFE4F348p-0115,),
    (-0x1.AF286BCA1AF28p-0005, -0x1.AF286BA50BE7Dp-0059, +0x1.B003B90E220F2p-0113,),
    (+0x1.8618618618618p-0005, +0x1.8616504219B96p-0059,),
    (-0x1.642C8590B2164p-0005, -0x1.3815F2D739882p-0060,),
    (+0x1.47AE147AE144Fp-0005, +0x1.96F16EA15BE79p-0060,),
    (-0x1.2F684BDA031C9p-0005, -0x1.232F871D05906p-0060,),
    (+0x1.1A7B95D031D44p-0005, -0x1.84E70CE6F98D2p-0059,),
    (-0x1.08415A818F2F4p-0005,),
    (+0x1.EE1931087A9F7p-0006,),
)

@generated _atan_polynomial(x::NTuple{N,T}) where {N,T} =
    _horner_expr_mf(_atan_coefficients(T, Val{N}()))

@inline _val(::Val{K}) where {K} = K

# Half-angle reduction: r <- r / (1 + sqrt(1 + r^2)), applied K times.
@inline _atan_reduce(r::_MF{T,N}, ::Val{0}) where {T,N} = r
@inline function _atan_reduce(r::_MF{T,N}, ::Val{K}) where {T,N,K}
    _one = one(_MF{T,N})
    next = r / (_one + sqrt(_one + r * r))
    return _atan_reduce(next, Val(K - 1))
end

@inline function Base.atan(x::_MF{T,N}) where {T,N}
    p = precision(_MF{T,N})
    hp = _half_pi(_MF{T,N})
    af = abs(first(x._limbs))
    _one = one(_MF{T,N})
    a = abs(x)
    big = a > _one
    r = ifelse(big, _one / a, a)                      # r in [0, 1]
    # For r <= tmax, evaluate directly: forming 1+r^2 with a small r
    # discards the low bits of r^2 and corrupts the reduced value.
    kv = _atan_halvings(T, Val(N))                    # Val{K}()
    in_range = first(r._limbs) > _atan_tmax(T, Val(N))
    t = ifelse(in_range, _atan_reduce(r, kv), r)      # t in [0, tmax]
    k = ifelse(in_range, _val(kv), 0)
    u = mfsqr(t._limbs, Val(N))                       # t^2
    q = _MF{T,N}(_atan_polynomial(u))                 # Q(t^2); P = 1 + t^2*Q
    base = unsafe_ldexp(t + t * (_MF{T,N}(u) * q), k) # 2^k * (t + t^3*Q)
    mag = ifelse(big, _half_pi(_MF{T,N}) - base, base)
    return ifelse(signbit(x), -mag, mag)
end

@inline function Base.atan(y::_MF{T,N}, x::_MF{T,N}) where {T,N}
    _zero = zero(_MF{T,N})
    pi_ = _pi(_MF{T,N})
    hp = _half_pi(_MF{T,N})

    # Divide the smaller magnitude by the larger so the ratio stays in [-1, 1]
    # When swapped, use atan(y/x) = sign(y/x)*pi/2 - atan(x/y).
    swap = abs(y) > abs(x)
    a = atan(ifelse(swap, x, y) / ifelse(swap, y, x))   # in [-pi/4, pi/4]
    ratio_neg = signbit(x) ⊻ signbit(y)
    base = ifelse(swap, ifelse(ratio_neg, -hp, hp) - a, a)

    # Quadrant: x < 0 shifts by +-pi (x == 0, y != 0 is handled by the swap).
    result = ifelse(signbit(x), base + ifelse(signbit(y), -pi_, pi_), base)
    # Origin: atan(+-0, +0) = +-0 ; atan(+-0, -0) = +-pi.
    origin = ifelse(signbit(x),
        ifelse(signbit(y), -pi_, pi_),
        ifelse(signbit(y), -_zero, _zero))
    return ifelse(iszero(x) & iszero(y), origin, result)
end
